name: Tell Us About Your Experience with the Living HHS Open Data Plan
description: This is a voluntary request for public inputs and comments on the Living HHS Open Data Plan with version 1.0 released by the U.S. Department of Health and Human Services (HHS) in July 2025. 
title: "[Feedback]: Living HHS Open Data Plan"
labels: ["feedback"]
assignees: 
 - alecblase
body:
- type: markdown
  attributes:
   label: |
    Thank you for your interest in the Living HHS Open Data Plan! This is a free-response sheet for sharing your feedback, ideas, or suggestions. Submissions will be publicly accessible online, so please follow the HHS Code of Conduct. You may answer the prompts below and/or comment on specific sections from the table of contents below.
- type: textarea
  attributes:
   label: |
    Identify gaps or omissions in the Living HHS Open Data Plan, including emerging technologies, Open Data trends, issues, or priorities that should be addressed in future updates.
   description: "Open-ended request for comments or feedback"
- type: textarea
  attributes:
   label: |
    Recommend best practices for data collection, management, or usage in open formats to help HHS achieve its Open Data goals, including intra-HHS data sharing and Real-World Data (RWD) exchanges.
   description: "Open-ended request for comments or feedback"
   render: shell
- type: textarea
  attributes:
   label: |
    Propose ideas or examples for piloting innovative data governance models with patients, industry, academia, and other sectors to improve health data governance and transparency.
   description: "Open-ended request for comments or feedback"
   render: shell
- type: textarea
  attributes:
   label: |
    Highlight public-private partnerships, collaborations, or cross-sector initiatives powered by HHS Open Data that deliver measurable impact and deserve inclusion in future versions of the Living Plan.
   description: "Open-ended request for comments or feedback"
   render: shell
- type: dropdown
  attributes:
   label: "Select any of the Living HHS Open Data Plan modules to submit comments or feedback to."
   options:
     - "HHS Objectives, Values, and Return on Investment (ROI) with Data"
     - "Unified HHS for Data Sharing",
     - "Data Collection Processes for Open Formats",
     - "Data Usage Information",
     - "Prioritizing Public Data Asset Review",
     - "Improving Processes for Meeting Open Data Goals",
     - "Intra-HHS Data Sharing — Be the Change",
     - "Real-World Data for Impact",
     - "Public-Private Partnerships with Transparency to Accelerate Impact",
     - "Public Engagement with, by, and for We the People",
     - "Appendix A - Acronyms, Definitions, Keywords, and Concepts",
     - "Appendix B - Novel Models of Data Governance: Inspired by Tribal Data Governance for Radical, Collective, Self-Governance",
     - "Appendix C - HHS Partnerships with Transparency",
     - "Appendix D - HHS Data Improvement Process - 2025 Status",
     - "Other (General Comments)"
   multiple: true 
